/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Iterator;
import javax.swing.JTextField;
import model.Album;
import model.Library;
import model.Playlist;
import model.Song;
import model.User;

/**
 *
 * @author Ignacio
 */
public class PlaylistForm extends javax.swing.JFrame {

    Library library;
    Playlist playlist;
    User user;

    public void assignAll(Playlist playlist, User user, Library library) {
        this.library = library;
        this.playlist = playlist;
        this.user = user;
    }

    /**
     * Creates new form createPlaylistForm
     */
    public PlaylistForm() {
        initComponents();
        setTitle("Detalles Playlist");
    }

    JTextField getjTextFieldNamePlayList() {
        return jTextFieldNamePlayList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSongPlaylistAlbum = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        jButtonRename = new javax.swing.JButton();
        jButtonDeletePlaylist = new javax.swing.JButton();
        listTotal = new java.awt.List();
        listActual = new java.awt.List();
        jButtonAddMedia = new javax.swing.JButton();
        jButtonDeleteMedia = new javax.swing.JButton();
        jTextFieldNamePlayList = new javax.swing.JTextField();
        jTextFieldRename = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jRadioButtonSong = new javax.swing.JRadioButton();
        jRadioButtonAlbum = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mis PlayLists");

        jButtonRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit (1).png"))); // NOI18N
        jButtonRename.setText("Renombrar");
        jButtonRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameActionPerformed(evt);
            }
        });

        jButtonDeletePlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jButtonDeletePlaylist.setText("Borrar Playlist");
        jButtonDeletePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePlaylistActionPerformed(evt);
            }
        });

        listTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTotalActionPerformed(evt);
            }
        });

        listActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActualActionPerformed(evt);
            }
        });

        jButtonAddMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add (2).png"))); // NOI18N
        jButtonAddMedia.setText("Añadir");
        jButtonAddMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMediaActionPerformed(evt);
            }
        });

        jButtonDeleteMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jButtonDeleteMedia.setText("Eliminar");
        jButtonDeleteMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteMediaActionPerformed(evt);
            }
        });

        jTextFieldNamePlayList.setEditable(false);
        jTextFieldNamePlayList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNamePlayList.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNamePlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamePlayListActionPerformed(evt);
            }
        });

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButtonBack.setText("Volver");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        buttonGroupSongPlaylistAlbum.add(jRadioButtonSong);
        jRadioButtonSong.setText("Canciones");
        jRadioButtonSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7_music_node.png"))); // NOI18N
        jRadioButtonSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSongActionPerformed(evt);
            }
        });

        buttonGroupSongPlaylistAlbum.add(jRadioButtonAlbum);
        jRadioButtonAlbum.setText("Álbumes");
        jRadioButtonAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8_audio_headphones.png"))); // NOI18N
        jRadioButtonAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlbumActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Librería");

        jLabel3.setText("Introduzca nombre");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleccione item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAddMedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDeleteMedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jRadioButtonSong)
                            .addComponent(jRadioButtonAlbum)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonDeletePlaylist)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(listActual, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRename, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRename)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldNamePlayList, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNamePlayList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(listActual, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddMedia)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonDeleteMedia)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonSong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAlbum))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldRename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonRename)
                                    .addComponent(jLabel3))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBack)
                            .addComponent(jButtonDeletePlaylist))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamePlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamePlayListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamePlayListActionPerformed

    private void jButtonRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameActionPerformed
        playlist.setName(jTextFieldRename.getText());
        jTextFieldNamePlayList.setText(jTextFieldRename.getText());
        jTextFieldRename.setText("");
    }//GEN-LAST:event_jButtonRenameActionPerformed

    private void jButtonDeletePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePlaylistActionPerformed
        user.removePlaylist(playlist.getName());
        InitialForm obj = new InitialForm();
        obj.assignAll(null, user, library);
        obj.setVisible(true);
        obj.ShowAllListaPlaylist();
        dispose();
    }//GEN-LAST:event_jButtonDeletePlaylistActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        InitialForm obj = new InitialForm();
        obj.assignAll(null, user, library);
        obj.setVisible(true);
        obj.ShowAllListaPlaylist();
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jRadioButtonSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSongActionPerformed

        listTotal.removeAll();
        Iterator<Song> iteratorSong = library.songs.iterator();
        while (iteratorSong.hasNext()) {
            listTotal.add(iteratorSong.next().getName());
        }
        listActual.removeAll();
        for (Song song : playlist.songs) {
            listActual.add(song.getName());
        }
    }//GEN-LAST:event_jRadioButtonSongActionPerformed

    private void listTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listTotalActionPerformed

    private void listActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActualActionPerformed
        if (jRadioButtonSong.isSelected()) {
            Song selected;
            selected = playlist.searchSong(listActual.getSelectedItem());
            SongForm obj = new SongForm();
            obj.assignAll(playlist, user, library, true, "Musica/Songs/");
            obj.getjTextFieldSong().setText(selected.getName());
            obj.setVisible(true);
            dispose();
        } else if (jRadioButtonAlbum.isSelected()) {
            Album selected;
            selected = playlist.searchAlbum(listActual.getSelectedItem());
            ChooseSong obj = new ChooseSong();
            String path = "Musica/Albums/"+selected.getName()+ " -"+selected.getArtist()+'/';
            obj.assignAll(selected, playlist, user, library, path);
            Iterator<Song> iteratorSong = selected.songs.iterator();
            while (iteratorSong.hasNext()) {
                obj.getlistCanciones().add(iteratorSong.next().getName());
            }
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listActualActionPerformed

    private void jRadioButtonAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlbumActionPerformed

        listTotal.removeAll();
        Iterator<Album> iteratorAlbum = library.album.iterator();
        while (iteratorAlbum.hasNext()) {
            listTotal.add(iteratorAlbum.next().getName());
        }
        listActual.removeAll();
        for (Album album : playlist.albums) {
            listActual.add(album.getName());
        }

    }//GEN-LAST:event_jRadioButtonAlbumActionPerformed

    private void jButtonAddMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMediaActionPerformed
        if (jRadioButtonSong.isSelected() && listTotal.getSelectedItem() != null) {
            Song selected;
            selected = library.searchSong(listTotal.getSelectedItem());
            if(selected != null){
                playlist.songs.add(selected);
                listActual.removeAll();
                for (Song song : playlist.songs) {
                    listActual.add(song.getName());
                }
            }
        } else if (jRadioButtonAlbum.isSelected() && listTotal.getSelectedItem() != null) {
            Album selected;
            selected = library.searchAlbum(listTotal.getSelectedItem());
            if(selected != null){
                playlist.albums.add(selected);
                listActual.removeAll();
                for (Album album : playlist.albums) {
                    listActual.add(album.getName());
                }
            }
        }
    }//GEN-LAST:event_jButtonAddMediaActionPerformed

    private void jButtonDeleteMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteMediaActionPerformed
        if (jRadioButtonSong.isSelected() && listActual.getSelectedItem() != null) {
            Song selected;
            selected = library.searchSong(listActual.getSelectedItem());
            if(selected != null){
                playlist.songs.remove(selected);
                listActual.removeAll();
                for (Song song : playlist.songs) {
                    listActual.add(song.getName());
                }
            }
        } else if (jRadioButtonAlbum.isSelected() && listActual.getSelectedItem() != null) {
            Album selected;
            selected = library.searchAlbum(listActual.getSelectedItem());
            if(selected != null){
                playlist.albums.remove(selected);
                listActual.removeAll();
                for (Album album : playlist.albums) {
                    listActual.add(album.getName());
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PlaylistForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSongPlaylistAlbum;
    private javax.swing.JButton jButtonAddMedia;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDeleteMedia;
    private javax.swing.JButton jButtonDeletePlaylist;
    private javax.swing.JButton jButtonRename;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonAlbum;
    private javax.swing.JRadioButton jRadioButtonSong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNamePlayList;
    private javax.swing.JTextField jTextFieldRename;
    private java.awt.List listActual;
    private java.awt.List listTotal;
    // End of variables declaration//GEN-END:variables
}
