/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Iterator;
import javax.swing.JOptionPane;
import model.Library;
import model.Playlist;
import model.User;

/**
 *
 * @author Ignacio
 */
public class ShowPlayList extends javax.swing.JFrame {
    Library library;
    User user;
    String cancionAlbum;
    
    public void assignUserLibrary(User user, Library library, String cancionAlbum) {
        this.user = user;
        this.library = library;
        this.cancionAlbum = cancionAlbum;
    }
    
    public void assignUserLibrary(User user, Library library) {
        this.user = user;
        this.library = library;
    }
    /**
     * Creates new form ShowPlayList
     */
    public ShowPlayList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listPlaylist = new java.awt.List();
        jButtonBack = new javax.swing.JButton();
        createPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Playlists");

        listPlaylist.setName(""); // NOI18N
        listPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPlaylistActionPerformed(evt);
            }
        });

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButtonBack.setText("Volver");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        createPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add (2).png"))); // NOI18N
        createPlaylist.setText("Crear playlist");
        createPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBack))
                    .addComponent(listPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(createPlaylist))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void listPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPlaylistActionPerformed
        Playlist selected;
        selected = user.searchPlayList(listPlaylist.getSelectedItem());
        if(library.searchSong(cancionAlbum) != null){
            selected.addSong(library.searchSong(cancionAlbum)); 
        }else if(library.searchAlbum(cancionAlbum) != null){
            selected.addAlbumPlaylistUser(library.searchAlbum(cancionAlbum));
        }        
        JOptionPane.showMessageDialog(null, "Contenido añadido a " + selected.getName());
        dispose();
    }//GEN-LAST:event_listPlaylistActionPerformed

    private void createPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaylistActionPerformed
        CreatePlaylistForm creaPlaylist = new CreatePlaylistForm();
        creaPlaylist.assignUserLibrary(user, library, false, cancionAlbum);
        creaPlaylist.setVisible(true);
        dispose();
    }//GEN-LAST:event_createPlaylistActionPerformed
    
    public void ShowAllListaPlaylist() {
        listPlaylist.removeAll();
        Iterator<Playlist> iteratorPlaylist = user.getPlaylist().iterator();
        while (iteratorPlaylist.hasNext()) {
            listPlaylist.add(iteratorPlaylist.next().getName());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPlayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ShowPlayList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPlaylist;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private java.awt.List listPlaylist;
    // End of variables declaration//GEN-END:variables
}
