/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.HeadlessException;
import java.io.*;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Library;
import model.Playlist;
import model.User;

/**
 *
 * @author Ignacio
 */
public class SongForm extends javax.swing.JFrame {

    Library library;
    Playlist playlist;
    User user;
    boolean vuelvePlaylist;
    
    Clip clip;
    boolean pausado = false;
    boolean reproduce = false;
    long tiempoPausado;
    String ruta;
    
    public void assignAll(Playlist playlist, User user, Library library, boolean vuelvePlaylist, String ruta) {
        this.library = library;
        this.playlist = playlist;
        this.user = user;
        this.vuelvePlaylist = vuelvePlaylist;
        this.ruta = ruta;
    }

    public JTextField getjTextFieldSong() {
        return jTextFieldSong;
    }

    /**
     * Creates new form SongForm
     */
    public SongForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldSong = new javax.swing.JTextField();
        jTextFieldReproductor = new javax.swing.JTextField();
        jButtonReproducir = new javax.swing.JButton();
        jButtonPausar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        addToPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre de la canción");

        jTextFieldSong.setEditable(false);
        jTextFieldSong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSongActionPerformed(evt);
            }
        });

        jTextFieldReproductor.setEditable(false);
        jTextFieldReproductor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonReproducir.setBackground(new java.awt.Color(0, 204, 0));
        jButtonReproducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4_audio_play (1).png"))); // NOI18N
        jButtonReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReproducirActionPerformed(evt);
            }
        });

        jButtonPausar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4_audio_pause.png"))); // NOI18N
        jButtonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausarActionPerformed(evt);
            }
        });

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        addToPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add (2).png"))); // NOI18N
        addToPlaylist.setText("Añadir a una playlist");
        addToPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldReproductor, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addToPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldReproductor))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVolver)
                            .addComponent(addToPlaylist)))
                    .addComponent(jButtonReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSongActionPerformed

    }//GEN-LAST:event_jTextFieldSongActionPerformed

    private void jButtonReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReproducirActionPerformed
        jTextFieldReproductor.setText("Reproduciendo");
        if(pausado && !reproduce){
            clip.setMicrosecondPosition(tiempoPausado);
            clip.start();
            pausado = false;
            reproduce = true;
        }else if(!pausado && !reproduce){
            String path = ruta+jTextFieldSong.getText()+" -"+library.searchSong(jTextFieldSong.getText()).getArtist()+".wav";
            try{
                File fich = new File(path);

                if(fich.exists()){
                    AudioInputStream audio = AudioSystem.getAudioInputStream(fich);
                    clip = AudioSystem.getClip();
                    clip.open(audio);
                    clip.start();
                    clip.loop(Clip.LOOP_CONTINUOUSLY);
                    reproduce = true;
                }else{
                    JOptionPane.showMessageDialog(null, "Ruta no encontrada");
                }
            }catch(UnsupportedAudioFileException | IOException | LineUnavailableException | HeadlessException ex){

            }
        }        
    }//GEN-LAST:event_jButtonReproducirActionPerformed

    private void jButtonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausarActionPerformed
        if(reproduce && !pausado){
            jTextFieldReproductor.setText("Pausado");
            tiempoPausado = clip.getMicrosecondPosition();
            clip.stop();
            pausado = true;
            reproduce = false;
        }
    }//GEN-LAST:event_jButtonPausarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        if(reproduce && !pausado){
            clip.stop();
        }
        if(vuelvePlaylist){
            PlaylistForm obj = new PlaylistForm();
            obj.assignAll(playlist, user, library);
            obj.getjTextFieldNamePlayList().setText(playlist.getName());
            obj.setVisible(true);
            dispose();
        }else{
            InitialForm obj = new InitialForm();
            obj.assignAll(null, user, library);
            obj.setVisible(true);
            obj.ShowAllListaPlaylist();
        }         
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void addToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPlaylistActionPerformed
        ShowPlayList show = new ShowPlayList();
        show.assignUserLibrary(user,library,jTextFieldSong.getText());
        show.setVisible(true);  
        show.ShowAllListaPlaylist();
    }//GEN-LAST:event_addToPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SongForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SongForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToPlaylist;
    private javax.swing.JButton jButtonPausar;
    private javax.swing.JButton jButtonReproducir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldReproductor;
    private javax.swing.JTextField jTextFieldSong;
    // End of variables declaration//GEN-END:variables
}
